### PR TITLE
[macOS, iOS] Log out on sync auth error

### LINKED ISSUE #205: Allow logging out
I could not try to reproduce 204 I could not reset the state of the app. If connecting to a new server, it would still use the same user.

It should
- [ ]  have a way to logout.
- [ ] show an error when the auth fails

@stel

### PR DESCRIPTION
**Pull request by stel**
This PR adds "Log out" menu item to macOS app and triggers logging out if sync session is not created or invalidated so there is no reason to remove the app from iOS device and reset macOS app when resetting the server anymore.

fixes #205 

/cc @jpsim, @TimOliver, @radu-tutueanu

### CODE REVIEW

**Comment by jpsim** [comment]
@dhmspector since you're now in charge of demo apps, I figure you might want to push for getting this reviewed?

**Comment by stel** [comment]
After https://github.com/realm/realm-cocoa/pull/4246 is merged this could probably be improved a bit as well as error reporting in general, but it's better to do that in different PR after those changes are released.

**Comment by TimOliver** [comment]
Sorry for the delay @stel!

This looks good, but after merging in the Swift 3 branch, some of the methods that this PR modifies have been renamed.

Let me know if you're swamped and I'll do it, but if you've got a free second, can you please update this from the `master` branch?

Thanks!

**Comment by stel** [comment]
Sure @TimOliver, will update this PR later this week!

**Comment by stel** [comment]
@TimOliver I'm stuck resolving conflicts here and have made a new PR #385. So I'm closing this one.

**Pull request closed without merging**
