### PR TITLE
Fix sandboxing in macOS app

### LINKED ISSUE #301: The RealmTasks for macOS app is not sandboxed
Sandboxing is broken in the app we build and deliver  as part of the bundle.
@stel @TimOliver

### PR DESCRIPTION
**Pull request by stel**
In this PR:

1. Entitlements files for different targets were renamed because of Xcode8 issue (it doesn't work well when those files have equal names)
2. Signing identity was set to "-" in macOS app and keychain sharing capability was removed. It allows to build the app with sandboxing enabled on any machine. Keychain sharing didn't work anyway and it's impossible to configure it because of different distribution options.
3. `package_release.rb` was updated to specify development team and signing identity, CI build was succeeded, app was signed and sandboxed.

Fixes #301 
/cc @TimOliver, @jpsim, @radu-tutueanu

### CODE REVIEW

**Comment by radu-tutueanu** [comment]
👍 Nice!

**Comment by TimOliver** [comment]
Awesome! Looks good! :+1:

**Comment by jpsim** [comment]
Sorry @stel, I merged #288 and now this needs to be updated.

**Comment by stel** [comment]
No worries @jpsim, updated.

**Comment by stel** [comment]
Stoped working on CI again :( https://github.com/realm/RealmTasks/pull/305/commits/3aba281f276bcb5346a03635dcab9bc9981a4203 was the last successful build, I can't see any big differences after merging `master` and I'm still able to build it locally, so to me it seems that this issue may be related to CI slaves. Will continue investigation, any help is appreciated.

**Comment by jpsim** [comment]
@stel can you please link to the CI failures you're referring to? I'd need that to help identify why this isn't working.

**Comment by stel** [comment]
Ok, now CI looks happy with CocoaPods `1.1.0.rc.2`.

**Pull request merged**
